services:
  app:
    image: ${DOCKER_IMAGE}:${VERSION}
    container_name: ${DOCKER_CONTAINER_NAME}
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /opt/secrets/google-recaptcha-enterprise-key.json
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      VERSION: ${VERSION}
      RECAPTCHA_PROJECT_ID: ${RECAPTCHA_PROJECT_ID}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_NAME: ${ADMIN_NAME}
      SUPADMIN_EMAIL: ${SUPADMIN_EMAIL}
      SUPADMIN_PASSWORD: ${SUPADMIN_PASSWORD}
      SUPADMIN_NAME: ${SUPADMIN_NAME}
    volumes:
      - media_data:/app/public/media
      - /opt/secrets/google-recaptcha-enterprise-key.json:/opt/secrets/google-recaptcha-enterprise-key.json:ro
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - jenahair-api
      - nginx-proxy-manager

  db:
    image: postgres:15
    container_name: jenahair_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jenahair-api

volumes:
  postgres_data:
  media_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/apps/jenahair.com/media
      o: bind

networks:
  jenahair-api:
    name: jenahair-api
    driver: bridge
  nginx-proxy-manager:
    external: true
